openapi: 3.0.3
info:
  title: Cardcashian API
  description: |
    A small Spring Boot REST API for managing "Cash Cards".
    
    Authentication: HTTP Basic. Only users with role CARD-OWNER can access the API.
  version: 0.0.1
servers:
  - url: http://localhost:8081
    description: Local development server
paths:
  /cashcards/{id}:
    get:
      summary: Get a CashCard by id
      operationId: getCashCardById
      security:
        - basicAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: CashCard found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CashCard'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden (user lacks role)
        '404':
          description: Not Found (unknown id or not owned by caller)
    put:
      summary: Update an existing CashCard (amount only)
      operationId: updateCashCard
      security:
        - basicAuth: []
      parameters:
        - name: requestedId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CashCardUpdate'
      responses:
        '204':
          description: Updated successfully
        '401':
          description: Unauthorized
        '403':
          description: Forbidden (user lacks role)
        '404':
          description: Not Found (unknown id or not owned by caller)
    delete:
      summary: Delete a CashCard by id
      operationId: deleteCashCard
      security:
        - basicAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Deleted successfully
        '401':
          description: Unauthorized
        '403':
          description: Forbidden (user lacks role)
        '404':
          description: Not Found (unknown id or not owned by caller)
  /cashcards:
    get:
      summary: List CashCards owned by the authenticated user
      operationId: listCashCards
      description: Returns a page slice (array) of CashCards for the current user. Supports paging and sorting.
      security:
        - basicAuth: []
      parameters:
        - name: page
          in: query
          description: Zero-based page index
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: size
          in: query
          description: Page size
          required: false
          schema:
            type: integer
            minimum: 1
            default: 20
        - name: sort
          in: query
          description: Sort criteria in the format `property,(asc|desc)`. E.g. `amount,asc`
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A list (page slice) of CashCards
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CashCard'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden (user lacks role)
    post:
      summary: Create a new CashCard
      operationId: createCashCard
      description: Creates a new CashCard for the authenticated user. Owner is taken from the principal; id is generated.
      security:
        - basicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CashCardCreate'
      responses:
        '201':
          description: Created. Location header points to the new resource.
          headers:
            Location:
              description: URL of the created CashCard resource
              schema:
                type: string
                format: uri
        '401':
          description: Unauthorized
        '403':
          description: Forbidden (user lacks role)
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    CashCard:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 99
        amount:
          type: number
          format: double
          example: 123.45
        owner:
          type: string
          example: sarah1
      required: [id, amount, owner]
    CashCardCreate:
      type: object
      properties:
        amount:
          type: number
          format: double
          example: 250.0
      required: [amount]
    CashCardUpdate:
      type: object
      properties:
        amount:
          type: number
          format: double
          example: 19.99
      required: [amount]
